const CLIENT_ACCESS_TOKEN = "KpFvMzAgzIhtoPWElRtcCyPRoHE06Y9nf6gEiqIl_UA3Y7BiE4ESy4rJQ4464-Bl"
const CLIENT_ID = "_xcMIbQi45SM01uqE3EKieQNqg3uCJhB84abXmkcm1QS6UreeloRjOpcQ_KadHjA"
const CLIENT_SECRET = "uXKllhnGZCgS5VLKQzcCQJuqj59W4yaZi2aQ9Aod8Ps1ig4B56w9OWZkCa5_SwAKJHf1a3SVhnLJu_VqwZqhew"
const REDIRECT_URI = ""
const RESPONSE_TYPE = "code"
const GRANT_TYPE = "authorization_code"

export {CLIENT_ACCESS_TOKEN, CLIENT_ID, CLIENT_SECRET, REDIRECT_URI, RESPONSE_TYPE, GRANT_TYPE}
  