var artists = [
    "Drake",
    "Taylor Swift",
    "The Weeknd",
    "Ed Sheeran",
    "Justin Bieber",
    "Ariana Grande",
    "Eminem",
    "Post Malone",
    "Kanye West",
    "Billie Eilish",
    "Coldplay",
    "Juice WRLD",
    "Dua Lipa",
    "Imagine Dragons",
    "Travis Scott",
    "Rihanna",
    "XXXTENTACION",
    "David Guetta",
    "Khalid",
    "Maroon 5",
    "Bruno Mars",
    "Kendrick Lamar",
    "Shawn Mendes",
    "Calvin Harris",
    "Sam Smith",
    "Daddy Yankee",
    "Beyoncé",
    "Queen",
    "Lana Del Rey",
    "Harry Styles",
    "Future",
    "One Direction",
    "Lady Gaga",
    "KAROL G",
    "J. Cole",
    "Chris Brown",
    "Adele",
    "Nicki Minaj",
    "The Chainsmokers",
    "Shakira",
    "Selena Gomez",
    "The Beatles",
    "Linkin Park",
    "Arctic Monkeys",
    "Halsey",
    "Sia",
    "Doja Cat",
    "Marshmello",
    "Katy Perry",
    "SZA",
    "Miley Cyrus",
    "Twenty One Pilots",
    "Avicii",
    "Metro Boomin",
    "21 Savage",
    "Camila Cabello",
    "Olivia Rodrigo",
    "Kygo",
    "Red Hot Chili Peppers",
    "Lil Baby",
    "OneRepublic",
    "Michael Jackson",
    "Myke Towers",
    "Jason Derulo",
    "Demi Lovato",
    "Mac Miller",
    "Feid",
    "Pitbull",
    "Morgan Wallen",
    "Tyler, The Creator",
    "Pop Smoke",
    "%24uicideboy%24",
    "Metallica",
    "Elton John",
    "Lil Peep",
    "BLACKPINK",
    "DJ Snake",
    "Ellie Goulding",
    "Alan Walker",
    "DaBaby",
    "Tiësto",
    "Lil Wayne",
    "Frank Ocean",
    "Lil Nas X",
    "Charlie Puth",
    "James Arthur",
    "Sech",
    "Young Thug",
    "YoungBoy Never Broke Again",
    "ABBA"
  ];

  export default artists
  